# Generated by Django 2.2.7 on 2019-12-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Director")),
            ],
            options={"verbose_name": "director", "verbose_name_plural": "Directores"},
        ),
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Nombre")),
                ("price", models.IntegerField(verbose_name="Precio")),
            ],
            options={
                "verbose_name": "plataforma",
                "verbose_name_plural": "Plataformas",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Titulo")),
                ("release", models.DateField(verbose_name="Estreno")),
                ("runtime", models.IntegerField(verbose_name="Duración")),
                ("episodes", models.IntegerField(null=True, verbose_name="Capitulos")),
                ("seasons", models.IntegerField(null=True, verbose_name="Temporadas")),
                ("description", models.TextField(verbose_name="Descripción")),
                ("poster", models.CharField(max_length=150, verbose_name="Poster")),
                ("imdbRating", models.CharField(max_length=6, verbose_name="IMDB")),
                (
                    "typeContent",
                    models.CharField(
                        default="Pelicula", max_length=10, verbose_name="Tipo"
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.Director"
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        default="Ninguno",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="db.Platform",
                    ),
                ),
            ],
            options={"verbose_name": "Contenido", "verbose_name_plural": "Contenido"},
        ),
    ]
