# Generated by Django 2.2.7 on 2019-11-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('release', models.DateField(verbose_name='Estreno')),
                ('runtime', models.IntegerField(verbose_name='Duración Episodio')),
                ('episodes', models.IntegerField(verbose_name='Capitulos')),
                ('seasons', models.IntegerField(verbose_name='Temporadas')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('poster', models.CharField(max_length=150, verbose_name='Poster')),
                ('imdbRating', models.CharField(max_length=6, verbose_name='IMDB')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'plataforma', 'verbose_name_plural': 'Plataformas'},
        ),
        migrations.DeleteModel(
            name='PlatformContent',
        ),
        migrations.AddField(
            model_name='serie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Director'),
        ),
        migrations.AddField(
            model_name='serie',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Platform'),
        ),
    ]
