# Generated by Django 2.2.7 on 2019-11-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20191129_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
