# Generated by Django 2.2.7 on 2019-12-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('release', models.DateField(verbose_name='Estreno')),
                ('runtime', models.IntegerField(verbose_name='Duración Episodio')),
                ('episodes', models.IntegerField(verbose_name='Capitulos')),
                ('seasons', models.IntegerField(verbose_name='Temporadas')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('poster', models.CharField(max_length=150, verbose_name='Poster')),
                ('imdbRating', models.CharField(max_length=6, verbose_name='IMDB')),
                ('typeContent', models.CharField(default='Pelicula', max_length=50, verbose_name='Tipo')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Director')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Platform')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
            },
        ),
        migrations.CreateModel(
            name='PlatformContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Content')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Platform')),
            ],
            options={
                'verbose_name': 'Contenido Plataforma',
                'verbose_name_plural': 'Contenido Plataformas',
            },
        ),
        migrations.RemoveField(
            model_name='serie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='platform',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
