# Generated by Django 3.0 on 2019-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20191212_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ManyToManyField(to='db.Genre', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='priceBasic',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Basico'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='pricePremium',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Premium'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='priceStandard',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio Estandár'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='resolutionBasic',
            field=models.CharField(max_length=10, verbose_name='Resolución Basico'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='resolutionPremium',
            field=models.CharField(max_length=10, verbose_name='Resolución Premium'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='resolutionStandard',
            field=models.CharField(max_length=10, verbose_name='Resolución Estandár'),
        ),
    ]
