# Generated by Django 3.0 on 2019-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191212_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sorting',
            field=models.CharField(default='+16', max_length=6, verbose_name='Clasificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='urlLogo',
            field=models.CharField(default='logo', max_length=150, verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformcontent',
            name='url',
            field=models.CharField(default='url', max_length=150, verbose_name='Enlace'),
            preserve_default=False,
        ),
    ]
