# Generated by Django 2.2.7 on 2019-12-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191201_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformContent',
        ),
    ]
