# Generated by Django 2.2.7 on 2019-12-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_delete_platformcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenido'},
        ),
        migrations.AlterField(
            model_name='content',
            name='runtime',
            field=models.IntegerField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='content',
            name='typeContent',
            field=models.CharField(default='Pelicula', max_length=10, verbose_name='Tipo'),
        ),
    ]
